// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: grpc-server/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_grpc_server_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_grpc_server_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_grpc_server_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_grpc_server_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_grpc_server_proto_user_proto protoreflect.FileDescriptor

const file_grpc_server_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x1cgrpc-server/proto/user.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x05Users\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.proto.UserR\x05users2A\n" +
	"\vUserService\x122\n" +
	"\bGetUsers\x12\x16.google.protobuf.Empty\x1a\f.proto.Users\"\x00B6Z4github.com/alimikegami/go-monorepo/grpc-server/protob\x06proto3"

var (
	file_grpc_server_proto_user_proto_rawDescOnce sync.Once
	file_grpc_server_proto_user_proto_rawDescData []byte
)

func file_grpc_server_proto_user_proto_rawDescGZIP() []byte {
	file_grpc_server_proto_user_proto_rawDescOnce.Do(func() {
		file_grpc_server_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_server_proto_user_proto_rawDesc), len(file_grpc_server_proto_user_proto_rawDesc)))
	})
	return file_grpc_server_proto_user_proto_rawDescData
}

var file_grpc_server_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_server_proto_user_proto_goTypes = []any{
	(*User)(nil),          // 0: proto.User
	(*Users)(nil),         // 1: proto.Users
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_grpc_server_proto_user_proto_depIdxs = []int32{
	0, // 0: proto.Users.users:type_name -> proto.User
	2, // 1: proto.UserService.GetUsers:input_type -> google.protobuf.Empty
	1, // 2: proto.UserService.GetUsers:output_type -> proto.Users
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_server_proto_user_proto_init() }
func file_grpc_server_proto_user_proto_init() {
	if File_grpc_server_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_server_proto_user_proto_rawDesc), len(file_grpc_server_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_server_proto_user_proto_goTypes,
		DependencyIndexes: file_grpc_server_proto_user_proto_depIdxs,
		MessageInfos:      file_grpc_server_proto_user_proto_msgTypes,
	}.Build()
	File_grpc_server_proto_user_proto = out.File
	file_grpc_server_proto_user_proto_goTypes = nil
	file_grpc_server_proto_user_proto_depIdxs = nil
}
